### PR TITLE
Adding additional functionality/ bugfixes

### PR DESCRIPTION
**Pull request by jleajones**
Allow sendbeacon method to be overridden with custom method.  In our case, we wanted to do dataLayer event pushes instead of ga.send() events.

Also, corrected a typo with the percent_played event and the fullscreen enter and exit were both firing "fullscreen_enter"

Finally, started a bower package to make it easy to install.

### CODE REVIEW

**Comment by mister-ben** [comment]
Thanks! Do you think you could you also add some documentation for using `sendbeaconOverride` to the README?

**Comment by jleajones** [comment]
Will do.

Quick question though...I noticed you forked from another repo, any plans
to get a pull request up to that repo?

Also, logging ad events are on our back log so you might get another PR
soon.

Thanks,
Jason

On Monday, April 20, 2015, mister-ben <notifications@github.com> wrote:

> Thanks! Do you think you could you also add some documentation for using
> sendbeaconOverride to the README?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mister-ben/videojs-ga-videocloud/pull/3#issuecomment-94585680>
> .
>


-- 
Jason Lea-Jones
www.jleajones.com | www.careymarcel.com

**Comment by mister-ben** [comment]
That's a good question. I'd initially kept this as a discrete fork as the changes for the Video Cloud player aren't relevant to a general video.js plugin - pulling name and id from mediainfo, dealing with the iframe embed, special-casing the Studio preview. My intention wasn't to become a blocker to contributions such as yours that are useful in a wider context from getting into the original plugin, which wouldn't be in keeping with the spirit of things. Interested in any thoughts on reconciling this, including from the original author @mickey.

**Comment by jleajones** [comment]
Makes sense...my only concern would be are you checking for updates to the original plugin, will modify my pull request today.

**Comment by nileshshrestha** [comment]
How do you pass a callback function for sendbeaconOverride as a json object? Passing it as string is throwing an error "D is not a function...". Looks like the source code is treating options not as JSON but javascript directly. The Brightcove UI however is check JSON format so we cannot pass function name in there.

**Pull request merged**
